### ISSUE TITLE
Add sample wavs to repo -- so that it is seldf contained.

### ISSUE THREAD

**Issue by cerkut** [NikolajAndersson/PEAQ#1]
Ideal pair: diode clipper with 16xFs anti-aliasing and  4xFs with or without anti-aliasing.
Thanks -- Cumhur

**Comment by NikolajAndersson** [comment]
I added 16xOversampling with anti-aliasing as ref and 4xOversampling with anti-aliasing as test. Both with guitar and diode clipper. 
Cheers
