### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by andimarafioti** [NikolajAndersson/PEAQ#2]
I think the algorithm actually comes from [this paper](http://www-mmsp.ece.mcgill.ca/Documents/Reports/2002/KabalR2002v2.pdf) by P. Kabal in 2002. It would be nice to have this cite on the readme:
Kabal, Peter. "An examination and interpretation of ITU-R BS. 1387: Perceptual evaluation of audio quality." TSP Lab Technical Report, Dept. Electrical & Computer Engineering, McGill University (2002): 1-89.

Note that this is mainly about the last name being 'Kabal' instead of 'Kabel'.

**Comment by NikolajAndersson** [comment]
Great, thanks! I have added your corrections. 
If you are working with PEAQ and the code, feel free to contribute. 

Cheers
