### ISSUE TITLE
odg value negative

### ISSUE THREAD

**Issue by pranaymanocha** [NikolajAndersson/PEAQ#3]
Hi!
Thanks for the repo. Much appreciated.
I was testing the code for two audio files and the odg value comes out to be something negative. As I understand, PEAQ values range is from 1-5 to mimic the human user. Can you verify if something is wrong with the code? Thanks!

**Comment by NikolajAndersson** [comment]
Hi, I haven't touched the algorithm, I simply uploaded it, since I needed it for a project. 
I think it is quite possible to break these types of algorithms, if you are not careful with the inputs. 
Feel free to look through the code and pull request if you find a bug :)

**Comment by pranaymanocha** [comment]
I even get negative values for the sample audio you have on the repo. Can you check if that's the same case for you? I have observed in the past that PEAQ requires higher sampling rate (typically 48KHz).

**Comment by NikolajAndersson** [comment]
Hello, 

I don't get negative values for the sample audio. As far as I remember, PEAQ needs 48kHz, which the sample audio indeed is :) I am not maintaining or using the code at all, so bugs can happen.

**Comment by pranaymanocha** [comment]
Thanks for the reply. Closing the issue

**Comment by NikolajAndersson** [comment]
Cool, no worries! If you have any updates/fixes, feel free to contribute :)
